### ISSUE TITLE
Forza Horizon 5 showing as no longer on Game Pass

### ISSUE THREAD

**Issue by brande77** [alike03/SubscriptionInfo#18]
https://store.steampowered.com/app/1551360/Forza_Horizon_5/
[screenshot](https://i.imgur.com/b8jvULu.jpeg)

Microsoft's games never leave Game Pass.

**Comment by alike03** [comment]
You have an old version of the extension installed. 
I noticed that by alike03's Sub Info Button positioning.
I moved that up, because on some languages it was disturbing the Search bar.
The up-to-date one is v1.2.2.3

![image](https://user-images.githubusercontent.com/8145921/175232375-2dfe37f5-7ac5-436a-854a-3719cd923352.png)
