### ISSUE TITLE
Future games not showing up for game pass

### ISSUE THREAD

**Issue by nategasm** [alike03/SubscriptionInfo#2]
Firstly, I love your add on!

Not sure if this is a bug or if the database is simply not updated but future games coming to game pass are currently not showing up. (Firefox)
For example this game: https://store.steampowered.com/app/1295510/DRAGON_QUEST_XI_S_Echoes_of_an_Elusive_Age__Definitive_Edition
Should have "Will be coming to Game Pass on 4th December 2020"

**Comment by alike03** [comment]
Thanks,

The database is same for all Browsers. The list is supplied by this site: https://www.xbox.com/en-US/xbox-game-pass/games
If it's not there the crawler removes it from the database. 
It was on the list once but XBOX removed it for some reason. I don't know why.
That's why the game doesn't show up as coming.

**Comment by alike03** [comment]
I made some research. Looks like Microsoft Store is more accurate compared to Xbox.
I'm planing to change the crawler to this site: https://www.microsoft.com/de-at/store/collections/pcgaVTaz?rtc=1
To avoid such problems.

**Comment by alike03** [comment]
Xbox enhanced the information available on https://www.xbox.com/en-US/xbox-game-pass/games and I adapted page scraper accordingly. 
This change is not necessary anymore.
